### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-ui-kit-page#2]
Нужно внести правки по запасному шрифту, как и в прошлом проекте

![Снимок экрана в 2019-09-24 15-20-45](https://user-images.githubusercontent.com/38564412/65511050-f1106400-dede-11e9-84c4-579da5ab4343.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
В about еще осталось
