### ISSUE TITLE
Повторяющиеся css-свойства

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-ui-kit-page#3]
Надо тебе как-то разобраться с IDE, чтобы подсвечивались вот такие моменты, может, плагин какой-то поставить. Ну и в голове тоже всегда нужно держать, что css-свойства не нужно повторять. В данном случае, например, вместо двух строк можно написать одну: `margin: 3.5rem 1rem 1rem`, потом в случае каких-то изменений будет удобнее править. 

![Снимок экрана в 2019-09-24 15-26-08](https://user-images.githubusercontent.com/38564412/65511513-0934b300-dee0-11e9-8c87-fddeb02646aa.png)

**Comment by Feinminen** [comment]
Внёс правки. Я до этого момента пытался убрать всё что повторялось, но таки не за всем уследил. Больше такой фигни не должно быть) И надо таки посмотреть почему VS-Code мне не подсвечивает свойства :\
