### ISSUE TITLE
Ссылки

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-ui-kit-page#7]
В стандартах указано, что 

> Для телефонов, емайл-адресов и скайп никнеймов нужно использовать `<a>` c соответствующим адресом

24 пункт https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md

Вот здесь нужно поправить:

![Снимок экрана в 2019-09-24 16-54-27](https://user-images.githubusercontent.com/38564412/65517832-fcb65780-deeb-11e9-9889-bf67451f25cd.png)

**Comment by Feinminen** [comment]
Внёс правки.
