### ISSUE TITLE
Home.js

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-ui-kit-page#8]
Сейчас у тебя класс `Home` знает об устройстве других блоков: 

![Снимок экрана в 2019-09-24 16-59-41](https://user-images.githubusercontent.com/38564412/65518280-b9a8b400-deec-11e9-9a72-cca26391d443.png)

То есть если у блоков что-то поменяется, то может поломаться `Home`. 

А также `Home` напрямую навешивает обработчики событий на другие блоки, добавляет и удаляет их классы. Всё это нарушает независимость компонентов.

Нужно это как-то поправить, чтобы блоки могли существовать независимо друг от друга, возможно, общались посредством публичных методов / событий.

**Comment by Feinminen** [comment]
Такс, я исправил, но что-то мне подсказывает, что делать нужно было не так :D

**Comment by MorganaLF** [comment]
Вот здесь есть ли вообще необходимость клики вешать на сами компоненты `arrow-button`? Может, повесить клик на обертки? Тогда не нужно будет лезть внутрь чужого компонента

![Снимок экрана в 2019-09-26 13-37-16](https://user-images.githubusercontent.com/38564412/65682086-e8489b00-e062-11e9-9d72-b66a3dbad640.png)

**Comment by MorganaLF** [comment]
Вот тут, в `Promo.js`, возможно лучше передать элемент, к которому прокручиваем, через параметры, так опять же можно будет избавиться от зависимости. К тому же тут снова непонятное наименование класса `js-second-screen`, не относящееся ни к какому блоку

![Снимок экрана в 2019-09-26 13-43-08](https://user-images.githubusercontent.com/38564412/65682506-c4398980-e063-11e9-8a64-b563a25a65f1.png)

**Comment by MorganaLF** [comment]
Для поиска элементов по DOM классы именуются так же, как и блоки/элементы, только с префиксом js. А у тебя сейчас откуда-то взялся класс `js-promo__start-screen`

![Снимок экрана в 2019-09-26 13-46-31](https://user-images.githubusercontent.com/38564412/65682739-37430000-e064-11e9-9dad-0122895705cd.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
В **Curriculum** ты все еще напрямую что-то делаешь со стрелками. Раз у тебя есть контейнеры, по которым происходит клик, то в зависимости от того, на каком контейнере клик, можно и определять, увеличиваем счетчик или уменьшаем. 

![Снимок экрана в 2019-09-27 15-34-14](https://user-images.githubusercontent.com/38564412/65769485-51501180-e13c-11e9-9c29-6e104355c827.png)

**Comment by MorganaLF** [comment]
**Promo**

Теперь у тебя тут появились миксы) Ты можешь использовать data-атрибуты, например, чтобы определять, какая кнопка какое назначение выполняет, если проблема в этом. 

![Снимок экрана в 2019-09-27 15-37-07](https://user-images.githubusercontent.com/38564412/65769707-e6eba100-e13c-11e9-910d-0307a1a07574.png)

**Comment by Feinminen** [comment]
> **Promo**
> 
> Теперь у тебя тут появились миксы) Ты можешь использовать data-атрибуты, например, чтобы определять, какая кнопка какое назначение выполняет, если проблема в этом.
> 
> ![Снимок экрана в 2019-09-27 15-37-07](https://user-images.githubusercontent.com/38564412/65769707-e6eba100-e13c-11e9-910d-0307a1a07574.png)

Я просто хотел объединить эти кнопки именно классами, чтобы они в js искались по одному селектору, который бы объяснял для чего собственно эти кнопки.
